### ISSUE TITLE
Snapshot X and Y values not written to file

### ISSUE THREAD

**Issue by aylakhan** [SCIInstitute/ALMA-TDA#28]
Test dataset is NGC404_CO21_briggs.pbcor.fits. It looks like X and Y values for the view are not being generated and written to the snapshot file:

Aylas-MacBook-Pro-4:alma ayla$ cat NGC404_CO21_briggs.pbcor.fits.snapshot
{
 "z1": 20,
 "zoom": 1
}Aylas-MacBook-Pro-4:alma ayla$

**Comment by PaulRosenPhD** [comment]
this is fixed in latest release
